model_name: single_player
dataset_converters: [CameraLinearConverterMatrixGame2]
network_config:
  target: src.models.singleplayer.world_model.SolarisSPModel
  params:
    action_config:
      blocks:
        [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
        ]
      enable_keyboard: true
      enable_mouse: true
      heads_num: 16
      hidden_size: 128
      img_hidden_size: 1536
      keyboard_dim_in: 23
      keyboard_hidden_dim: 1024
      mouse_dim_in: 2
      mouse_hidden_dim: 1024
      mouse_qk_dim_list: [8, 28, 28]
      patch_size: [1, 2, 2]
      qk_norm: true
      qkv_bias: false
      rope_dim_list: [8, 28, 28]
      rope_theta: 256
      vae_time_compression_ratio: 4
      windows_size: 3
      left_action_padding: 11 # change from 12 to allow action i to influence frame i
    dim: 1536
    eps: 1e-06
    ffn_dim: 8960
    freq_dim: 256
    in_dim: 36
    inject_sample_info: false
    model_type: "i2v"
    num_heads: 12
    num_layers: 30
    out_dim: 16
    text_len: 512
    local_attn_size: 6
    platform: ${device.name}
