defaults:
  - shared
  - device: gpu
  - model: solaris
  - runner: inference
  - dataset@eval_datasets.eval_structure: eval_structure
  - dataset@eval_datasets.eval_translation: eval_translation
  - dataset@eval_datasets.eval_rotation: eval_rotation
  - dataset@eval_datasets.eval_turn_to_look: eval_turn_to_look
  - dataset@eval_datasets.eval_turn_to_look_opposite: eval_turn_to_look_opposite
  - dataset@eval_datasets.eval_both_look_away: eval_both_look_away
  - dataset@eval_datasets.eval_one_looks_away: eval_one_looks_away

  - _self_
