train_dataset_name: ""
test_dataset_name: "eval/bothLookAwayEval/test"
class: src.data.dataset.DatasetMultiplayer
name: eval_both_look_away
multiplayer: true
additional_params:
  bot1_name: "Alpha"
  bot2_name: "Bravo"
  shuffle_bots: ${shuffle_bots}

