train_dataset_name: ""
test_dataset_name: "eval/turnToLookOppositeEval/test"
class: src.data.dataset.DatasetMultiplayer
name: eval_turn_to_look_opposite
multiplayer: true
additional_params:
  bot1_name: "Alpha"
  bot2_name: "Bravo"
  shuffle_bots: ${shuffle_bots}

